name: xpirax
description: A Point of Sales Desktop and Android Application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  # path_provider_ex: ^1.0.1
  sqlite3_flutter_libs: ^0.5.9 
  http: ^0.13.4
  sqflite: ^2.0.2
  syncfusion_flutter_charts: ^20.2.49
  charts_flutter: ^0.12.0
  provider: ^6.0.2
  flutter_offline: ^2.1.0
  sqflite_common_ffi: ^2.1.0+2
  uuid: ^3.0.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  filesystem_picker: ^3.1.0
  open_file: ^3.2.1
  intl: ^0.17.0
  font_awesome_flutter: ^10.3.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.2
  path:
  pdf: ^3.7.1
  printing: ^5.7.2
  # window_size:
  #   git:
  #     url: git://github.com/google/flutter-desktop-embedding.git
  #     path: plugins/window_size
  #     ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.10.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/xpirax_logo/logo.png"



flutter:  
  uses-material-design: true
  assets:
  - assets/xpirax_logo/logo.png

msix_config:
  display_name: Spiral Point of Sales Software
  publisher_display_name: Xpirax Technologies Limited
  identity_name: company.suite.flutterapp
  msix_version: 1.0.0.0
  logo_path: C:\Users\lenovo\Desktop\projects\spiral_pos\installers\spiral_logo.ico
  capabilities: internetClient, location, microphone, webcam
  app_installer: #<-- app installer configuration
    publish_folder_path: C:\Users\lenovo\Desktop
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false

